apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
data:
  database: {{ .Values.app.database | b64enc }}
  authDomain: {{ .Values.app.authDomain | b64enc }}
  authAudience: {{ .Values.app.authAudience | b64enc }}
  appDomain: {{ .Values.app.appDomain | b64enc }}
